version: "3.9"
  
services:
  mongo:
    image: mongo
    container_name: dnd_mongo
    ports:
      - 27018:27017
    volumes:
      - ./volumes/mongo:/data/db
      
  rabbitmq:
    image: rabbitmq
    container_name: dnd_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=wowuser
      - RABBITMQ_DEFAULT_PASS=password
   
  postgresql:
    image: postgres
    container_name: dnd_postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dnd_postgresql
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: dnd_backend
    ports:
      - 8080:8080
    environment:
      - EnableDataSeed=true
      - MongoDbSettings__Host=host.docker.internal
      - MongoDbSettings__Port=27018
      - RabbitMqSettings__Host=host.docker.internal
      - RabbitMqSettings__Username=wowuser
      - RabbitMqSettings__Password=password
      - ASPNETCORE_ENVIRONMENT=Development
      - FrontendHost ="http://localhost:3000/"
      - ConnectionStrings__LogsPostgresql=Host=host.docker.internal;Database=dnd_postgresql;Username=user;Password=123
    depends_on:
      - mongo
      - rabbitmq
      - postgresql

  frontend:
    build:
      context: ./frontend/DnD
      dockerfile: ./Dockerfile
    container_name: dnd_frontend
    environment:
      - VITE_GRAPHQL_HOST=http://localhost:8080/graphql
      - VITE_HUB_HOST=http://localhost:8080/gamehub
    ports:
      - 3000:3000
    